apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: prod

resources:
- app
- argocd

images:
- digest: sha256:dbe55640670779f15ce353482a58a60e2c1c92078ccd9f108a330bfb7a0869bd
  name: quay.io/tstockwell/greeting-ui
